/*
 * precompiled.h
 *
 *  Created on: 29.02.2020
 *      Author: doene
 */

#ifndef REPS_HERP_FRONTENDINTERFACE_HERP_FRONTENDINTERFACE_PRECOMPILED_H_
#define REPS_HERP_FRONTENDINTERFACE_HERP_FRONTENDINTERFACE_PRECOMPILED_H_

#include <HERP.FrontendInterface.Export.h>
#include <QxOrm.h>
#include <OData>

#endif /* REPS_HERP_FRONTENDPROVIDER_HERP_FRONTENDPROVIDER_PRECOMPILED_H_ */
